### ISSUE TITLE
Glitchy elements with 2 workspaces

### ISSUE THREAD

**Issue by thr23** [compiz-reloaded/compiz-plugins-experimental#11]
When using two horizontal workspaces with stars, fireflies, snow or elements plugins enabled, visual glitches constantly appear while rotating the cube.

![workspace_1_014](https://cloud.githubusercontent.com/assets/21966696/18223292/176c6e24-71b3-11e6-91d2-c761ecaa66ff.png)

**Comment by soreau** [comment]
I'm not sure exactly why this happens yet but you should be able to temporarily fix this by disabling draw over windows. Interestingly enough, the opposite is true for the standalone snow plugin.

**Comment by thr23** [comment]
It's lots better with draw over windows disabled in elements (or enabled in separate plugins, like you said), but elements and their separate plugins are still glitching a bit for me. Though much less, and mostly right while starting the rotation. Might be something with my setup, will check on a different machine in a bit.
I 'think' these effects used to work fine some time ago, but it was a long time since, so it doesn't say much.

Aand btw, is there still need for separate snow/bubbles etc plugins? Looks like all of their features have been integrated into elements by now.

**Comment by soreau** [comment]
@thr23 Can you test this patch? https://gist.github.com/soreau/4b60e16007642f00fa08f0b7d76ae3d2

It is very much a wip but fixes the 2-face cube problem along with step adjustment to improve smoothness. With this, speed controls wont work and the speed might vary depending on load, this is expected and would be hooked up to use elapsed ms between frames to smooth it out. To test with expo, you need to make sure elements is loaded after expo in ccsm>preferences>plugin sorting (right column) after installing with the patch and restarting compiz. If not, manually move it, re-enable automatic sorting and restart compiz and ccsm. There a few corner cases left to be ironed out, namely that it draws incorrectly above cube and expo.

The right-when-starting-rotation glitch still happens, though I can reproduce it at least.

**Comment by soreau** [comment]
@ethus3h You might be interested in this patch as well, since you reported compiz-plugins-experimental issue #14 and it changes the rendering.

**Comment by thr23** [comment]
The patch seems to work, this constant rotation glitching on 2 workspaces is gone. Minor glitching still sometimes happens when rotating starts, and also right when it ends, but it's a bit elusive and hard to reproduce now. Seems like the most sure way to get it is to (re)start Compiz and try rotating right then.

And it looks like another glitch came up with a 2-workspace cube. It was there before the patch as well, but it looked like a part of the main problem. Now it turned out to be some kind of clash with animation plugins. It's there with wobbly windows and with dodge and with magic lamp, etc. This one creates very distinctive patterns, which depend on the type of animation used. Here's what it looks like when minimizing a wobbly window:
![workspace07](https://cloud.githubusercontent.com/assets/21966696/18612306/023203e8-7d57-11e6-9d0a-ff6e05541c8c.png)

Also checked out the issues with expo, while I was at it, and it looks like the textures are no longer being drawn by the elements plugin after the patch. On this shot, white blocks come from the snow in the post-patch elements plugin, and the pretty snowflakes from the separate snow plugin. It also looks like the particles are no longer drawn on the whole expo screen, they're limited to a certain area around their workspaces. It doesn't seem to change anything whether elements is before or after expo in the plugins list.
![workspace005](https://cloud.githubusercontent.com/assets/21966696/18612417/8bb2ecf2-7d59-11e6-9505-4c377c73996c.png)

**Comment by soreau** [comment]
Thanks for testing, and for the screeshots.

How are you wobbling, (un)minimizing, (un)maximizing a window while rotating cube?

White squares usually mean the texture isn't being loaded correctly, did you verify the textures in the snow list are present? Elements also has to be loaded after the image loading plugins, jpeg, png and svg. Run compiz from a terminal or enable error notifications and see if there is any interesting output.

**Comment by thr23** [comment]
Sorry, it's the other way around, I'm (un)maximizing the window, THEN rotating the cube, while the window is still animating. While the animation goes on, rotating the 2-faceted cube causes the animated window and the whole screen to glitch, and when the animation stops, the glitching stops as well. Wobbly windows plugin defaults are a bit fast, but you should still be able to see the distortions if you rotate quickly after unmaximizing a window. It's easy to see with minimum friction and maximum spring set in wobbly windows.
It's the same with the other animation plugins, try setting a long animation time for magic lamp, minimizing a window then rotating. The pattern is different with every animation, here you can see distinctive slashes going through the window animated with the magic lamp effect:
![workspace004](https://cloud.githubusercontent.com/assets/21966696/18613454/974e4eae-7d7b-11e6-9305-b62c312a6850.png)

About expo: the textures load fine and look fine on a normal screen or while rotating, it's only in expo mode that snowflakes, leaves, stars etc. turn into blocks. Elements is loaded as the last plugin on my plugins list, and no useful info comes up even with max log level set to debug in error reporting plugin. Just the standard "Info: Loaded Texture" messages.

**Comment by soreau** [comment]
Ah right, I see what you mean. Can you see if [this](https://gist.github.com/soreau/6ac3ed6b2fc3c4d53e70e7fb3e663a7d) fixes the visual glitches you're seeing? It's a patch for compiz.

**Comment by thr23** [comment]
Indeed it does, the glitches are gone. With this patch another thing came up though. When (un)maximizing the window, several reflections are drawn at different angles around the cube. It was introduced by that latest patch and happens only during animations on a rotated screen, but it's no longer isolated to 2-workspace scenario and happens with a traditional cube as well:
![workspace010](https://cloud.githubusercontent.com/assets/21966696/18614092/2dedd616-7d88-11e6-876c-d1dcbb279db1.png)

**Comment by soreau** [comment]
This problem doesn't seem to happen with 3D Windows enabled.. set window depth to 0 and window space to 1 for minimal effect. Further debugging is needed to figure out what's really going on.

I'm still a bit puzzled as to why it draws white squares in expo, that doesn't happen here. FWIW, here's the Default.ini I'm using http://hastebin.com/iyelinehar.ini

**Comment by soreau** [comment]
@thr23 Care to give this one a go? https://gist.github.com/soreau/0dea22b7b66a54b53e0a0e11b7f07a67 It should fix the annoying problem of snowflakes moving/appearing/disappearing suddenly when moving across the edge of a cube face and maybe fixes expo with draw over windows.

**Comment by thr23** [comment]
This patch seems to fix the clipping problems in issue #14 . Can't be sure, because I'm still seeing white squares, but they look like they are being drawn like they should between the workspaces, even with vp_distance in expo set to 1. However, while the patch seems to extend the particles draw area somewhat, they're still not being drawn on the whole screen. Try setting distance to a non-default value in expo settings. On these shots, distance was set to a maximum (1). Snowflakes come from the original snow plugin, and are drawn on the whole screen; white squares come from the snow module of elements plugin, and are drawn just in a certain area around the workspaces in expo mode.
![workspace001](https://cloud.githubusercontent.com/assets/21966696/18621172/d056c65a-7e1f-11e6-90b8-75eebc35f82e.png)
![workspace002](https://cloud.githubusercontent.com/assets/21966696/18621285/324614d2-7e21-11e6-81c4-7ff10527617e.png)

About the original issue: enabling 3d windows does seem to work in case of a traditional cube, and no nasty reflections are being drawn. The thing is, 3d windows don't work in a 2-workspace scenario at all. Was actually meaning to open another issue for that.

**Comment by thr23** [comment]
Toggling mipmaps off in expo makes the textures show as intended.
![workspace016](https://cloud.githubusercontent.com/assets/21966696/18621794/98f66dba-7e28-11e6-8933-cb2f1d6b0217.png)

**Comment by thr23** [comment]
It turns out that I was in the wrong, and the issues with these strange reflections were not introduced by your newest patches after all. I've tried it on a different machine with fresh Compiz from git, but haven't applied the patches from this thread yet, and these ugly reflections are here anyway.
So the thing with reflections seems to be a separate issue, and it's not connected to using 2 workspaces, so I guess this issue can be marked as solved and closed at your leisure. Unless some more testing is still needed. Aand kudos for fixing much more than was reported, really appreciate what you did.

**Comment by soreau** [comment]
Yes, I tested expo with mipmaps + snow with no patches, latest git, and it still renders white squares. This and the 'strange reflection issue' are separate bugs. I am pretty sure the latter is a problem with the 3D plugin. The mipmapping problem I haven't tried to debug.

The particle area is just a #define in the source, that could be made configurable relatively easily.
